[package]
name = "bevy_nursery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10"
ron = "0.8"
serde = "1"
thiserror = "1"